import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/shared-components/Footer'

export const metadata: Metadata = {
  title: 'Momtan Next App',
  description: 'Generated by create next app',
}

// If loading a variable font, you don't need to specify the font weight
const rubik = Rubik({
  subsets: ['latin', 'arabic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar">
      <body
        className={`${rubik.className} antialiased inset-0 relative bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]`}
      >
        <div
          className="absolute left-0 right-0 top-0 -z-10 m-auto h-full w-full 
        rounded-full bg-fuchsia-200 opacity-30 blur-[100px]"
        ></div>

        <Header />

        {children}
        <Footer />
      </body>
    </html>
  )
}
